server:
  port: 8181
  tomcat:
    uri-encoding: UTF-8
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: list
    filter: true
    enabled: true

spring:
  profiles:
    group:
      "loc": "loc"
      "dev": "dev"
      "prd": "prd"
---

spring:
  config:
    activate:
      on-profile: "loc"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: dba
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false # 트랜잭션 종료시 영속성 해제 기본값 true(영속성 유지)
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

debug: true



